const { pseudoRandomBytes } = require('crypto')
const os = require('os')
console.log('Операционная система', os.platform())
console.log('Архитектура процессора', os.arch())
console.log('Информация о процессорах', os.cpus())
console.log('свободная память', os.freemem())
console.log('всего памяти', os.totalmem())
console.log('Домашняя директория', os.homedir())
console.log('Время работы', os.uptime())